namePrefix: iter8-
resources:
- configmaps
- github.com/iter8-tools/etc3/config/crd/
- github.com/iter8-tools/etc3/config/rbac-iter8/
- github.com/iter8-tools/etc3/config/manager/
# To use a tagged release, for example v0.1.0-rc, change main to v0.1.0-rc in the above three lines

images:
- name: iter8/etc3:latest
